### ISSUE TITLE
AutoUpgrade freezes the browser

### ISSUE THREAD

**Issue by GreatOldOne** [SteamDatabase/steamSummerMinigame#157] opened 2015-06-15 18:16 UTC
Still there, even after the patches.

**Comment by xPaw** [comment] 2015-06-15 18:17
Any errors in the console?

**Comment by GreatOldOne** [comment] 2015-06-15 18:18
It freezes before I can debug, so no.

**Comment by xPaw** [comment] 2015-06-15 18:18
Then we can't really help you.

**Comment by rossengeorgiev** [comment] 2015-06-15 18:18
Does it work if you uncheck both autoupgrades?

**Comment by GreatOldOne** [comment] 2015-06-15 18:19
Yes, it seems to work just fine if I uncheck them.

**Comment by rossengeorgiev** [comment] 2015-06-15 18:22
Are you running 4.4.1+ ?

**Comment by GreatOldOne** [comment] 2015-06-15 18:23
Yup, after your patch it didn't freeze right away (I could still check the console on that one).
However, now it runs for a bit and freezes the whole browser (possible memory leak with the implementation)?
Haven't froze yet with them unchecked.

**Comment by sordidfellow** [comment] 2015-06-15 18:27
Confirmed latest version (4.4.1)in chrome definitely freezes browser.

**Comment by K4r0qtuYNE5G4qgZ** [comment] 2015-06-15 18:27
jut updated freezes everything slowmotion, everything is unchchecked also, chrome too btw.

**Comment by xPaw** [comment] 2015-06-15 18:28
"slowmotion" is throttled renderer, it's not a bug.

**Comment by Rawrlex** [comment] 2015-06-15 18:28
Works fine for me, Chrome 64 Bit. All boxes checked.

**Comment by GreatOldOne** [comment] 2015-06-15 18:30
It freezes for me on Chrome 64-bits with 8 GB DDR3.

**Comment by K4r0qtuYNE5G4qgZ** [comment] 2015-06-15 18:30
ohh, ok, well 4.2.1 before after 4.4.1 everything slowmotion, can the throtteled renderer be disabled?

EDIT: ok thanks, yeah disabled it and works, no freezing, chrome 64bit too...

**Comment by GreatOldOne** [comment] 2015-06-15 18:31
Uncheck Throttle game renderer,

**Comment by sordidfellow** [comment] 2015-06-15 18:32
I had just the default set of boxes checked.  (AutoClicker, remove interface, particle effect, flinching effects, throttle renderer, auto-refresh, targeting pointer).
Turning on just "Enable AutoUpgrade Clicks" from that set causes the page/to completely lock up.  Had to reload page and click the box to turn it off, and then reload the page again to get back to a functioning state,

**Comment by GreatOldOne** [comment] 2015-06-15 18:33
If the browser doesn't entirely freezes for you, could you please show the error displayed in the console (if any)?

**Comment by K4r0qtuYNE5G4qgZ** [comment] 2015-06-15 18:33
i not turned on auto upgrade yet, so can't confirm anything related to it...

**Comment by Xinayder** [comment] 2015-06-15 18:34
Confirmed, it freezes the browser for a while, but after a few milliseconds it gets unstuck.

**Comment by sordidfellow** [comment] 2015-06-15 18:36
On a new game with very few abilities and low levels, the lag/lockup doesnt seem to happen.

**Comment by K4r0qtuYNE5G4qgZ** [comment] 2015-06-15 18:38
so perhaps related to going crazy?

**Comment by GreatOldOne** [comment] 2015-06-15 18:41
No, that's only triggered in the final minutes of the game.
And that was added before today's reset, and worked just fine with the final moments.

**Comment by K4r0qtuYNE5G4qgZ** [comment] 2015-06-15 18:45
ok.

**Comment by Allimon** [comment] 2015-06-15 18:48
This is an error I'm experiencing, the game still runs; however, it feels much slower than before. Version is 4.1.1. I'm also not sure if this error is completely related to this issue nor if it is new.

![steam summer game error](https://cloud.githubusercontent.com/assets/6963144/8167611/02bd5932-1365-11e5-9664-2b91d3b3096e.png)

**Comment by GreatOldOne** [comment] 2015-06-15 18:54
That's a problem with the minigame itself, not this script.

**Comment by rossengeorgiev** [comment] 2015-06-15 20:38
I can't reproduce this, probably not caused by AutoUpgrade feature. Does anyone still experience the problem when all AutoUpgrade options are disabled?

**Comment by GreatOldOne** [comment] 2015-06-15 21:56
No, haven't frozen for me ever since I disabled AutoUpgrade.

**Comment by K4r0qtuYNE5G4qgZ** [comment] 2015-06-15 23:44
i have it disabled all the Time no freezes so far running fine 5 Hours now across all updates.

**Comment by iakat** [comment] 2015-06-15 23:47
Closing as this is not reproducible.

**Closed as completed by iakat** 2015-06-15 23:47 UTC
Labels: Bug, Needs Testing
