### ISSUE TITLE
Autobuy Cheapest Upgrade

### ISSUE THREAD

**Issue by ghost** [SteamDatabase/steamSummerMinigame#85] opened 2015-06-14 16:53 UTC
If Clicking messes up the autoplayer and the goal is efficiency, then we need some way of the game simply buying the cheapest available upgrade to continue effective progression without crippling the script itself.

**Comment by Scrxtchy** [comment] 2015-06-14 16:57
The idea is to not click on the enemies.
Clicking on the store should work fine

**Comment by wchill** [comment] 2015-06-14 16:58
You probably want to also not consider the AFK abilities as they're going to be useless

**Comment by iakat** [comment] 2015-06-14 19:04
Duplicate of #79.

**Comment by iakat** [comment] 2015-06-14 19:09
Whoops, it's not, my bad.

**Comment by HxxxxxS** [comment] 2015-06-14 19:11
Suggesting renaming/rebranding this as Autobuy **Most Cost Effective** Upgrade. 

Edit: Most health incrase / cost, most damage increase / cost

**Comment by thlac** [comment] 2015-06-14 19:46
Maybe also prioritise tier progression over cost effectiveness to begin with.

**Comment by sithrebel15** [comment] 2015-06-14 20:25
SteamDatabase/steamSummerMinigame/pull/89

Buys the most cost effective upgrade for you.

**Comment by xPaw** [comment] 2015-06-15 17:59
Closed by #153

**Closed as completed by xPaw** 2015-06-15 17:59 UTC
Labels: 2 - Medium Priority
