### ISSUE TITLE
Improve end-game wormhole logic

### ISSUE THREAD

**Issue by iakat** [SteamDatabase/steamSummerMinigame#190] opened 2015-06-15 23:57 UTC
The best idea would be by getting the amount of wormhole a player has, and start using them in (number_of_wormholes + X minutes) to the end of the game.

**Comment by Xinayder** [comment] 2015-06-15 23:59
And we should use every ability we have that is cooled down when the game is near end.

**Comment by squee666** [comment] 2015-06-15 23:59
Would be nice if you had a system that did this and generated a _spend everything mode_

Say 1hour before your Wormholes began it would spend everything dmg wise etc like throw money.

**Comment by GreatOldOne** [comment] 2015-06-15 23:59
The problem is not even that wormholes stack (also need proof for that), but that we want to delay their use as much as we can, so the final higher levels goes out within a second or two.

**Comment by GreatOldOne** [comment] 2015-06-16 00:00
Somethings need to be left for the user to decide. Automation of everything is not always a good idea.

**Comment by GreatOldOne** [comment] 2015-06-16 00:04
Also remember that after we exhaust our wormholes, we will exhaust any throw money we have.

**Comment by squee666** [comment] 2015-06-16 00:05
Wouldnt it be better to exhaust Money and items before wormholes because of level scaling on mobs?(do they level scale)

I mean Room 1 has 14.7k wormholes so you are literally jumping from lvl 30k to 45k in end

**Comment by GreatOldOne** [comment] 2015-06-16 00:07
Yes, but I guess you could use the time during wormhole usage to build more money.

**Comment by GreatOldOne** [comment] 2015-06-16 00:08
And I don't think it will be able to jump that fast...
1 hour = 3600 seconds, consider each wormhole taking 1 second. Do you see the problem?

**Comment by squee666** [comment] 2015-06-16 00:11
Well if wormholes do stack. it would take 5minutes or less to spend them all if they are affected by Cooldown reduction items

**Comment by kaetemi** [comment] 2015-06-16 05:52
I would recommend ((1.1min\* nb wormholes) + 30min), some extra overhead per wormhole to cope with delays between cooldown deactivation, and relock them again 15min before end. Then after the wormholes have completed start throwing money, since throw money during wormholes is a waste.

**Comment by Sosseres** [comment] 2015-06-16 06:27
There is also the chance that the room you are in will be closed before the end time since they bring them down one by one instead of all at once. I would suggest being done at least 10 min before the end time.

**Comment by rlabrecque** [comment] 2015-06-16 06:30
Don't forget about people that have a large amount of wormholes. With the minute cooldown on them blindly starting 10 minutes before would suck for people that have 10+

**Comment by kaetemi** [comment] 2015-06-16 06:38
Hence the + 30 minutes extra time

**Comment by GreatOldOne** [comment] 2015-06-16 09:14
That PR shouldn't have been merged, instead we should've allowed for more than an hour.
I'll submit a new PR allowing the user to set more than 60 minutes, hopefully it gets merged.

**Comment by GreatOldOne** [comment] 2015-06-16 09:18
Another bad merge, because throw money also relies on isNearEndGame().

**Comment by GreatOldOne** [comment] 2015-06-16 09:18
Do not alter isNearEndGame() for wormholes only!

**Comment by 3xo** [comment] 2015-06-16 14:01
Right now, we are spamming 'throw money' when running out of wormholes. But that doesnt necessarily mean all wormholes are already processed. People have different amount of wormholes, hence some will immediatly start throwing money while some have to use their 30+ wormholes +cooldown first.

Their should be a check if there is >1 wormhole active in lane, and when true stop using any other item/ability.
This also prevents wasting items/abilities when someone manully fires WH at any time of the game.

Edit: 
if(tryUsingAbility(ABILITIES.WORMHOLE, true))
-> doesnt this mean we are checking if there are any active wormholes in lane and thus limiting to 1 WH per lane? I thought WHs should be stacked?

pls correct me if i'm mistaken

**Comment by mueslo** [comment] 2015-06-16 15:34
@3xo Aren't wormholes applied instantly? In that case it doesn't make sense to check if they are active.
@GreatOldOne we know wormholes stack simply from the high rate of leveling at the endgame, With 4 levels per second or more. Since the tickrate is 1s, you can at most get 1 level per second without wormholes.

**Comment by 3xo** [comment] 2015-06-16 15:38
Yes i doesnt make sense, the check is removed as of 4.6
I still think there should be a timeframe were only WH are being used and no other items. After that period all remaining items are spammed as suggested in #226

**Comment by mueslo** [comment] 2015-06-16 15:43
@3xo items should be spammed before wormholes, since it's easier leveling.

**Comment by milkfat** [comment] 2015-06-16 20:06
Wormholes should now be activated on Raining Gold levels which are divisible by 100. Wormholes stack and aren't activated until the level is completed. Using them during Raining Gold levels will give us the best chance of hitting the target to skip 10 levels.

**Closed as completed** 2015-06-18 11:47 UTC
Labels: Help Wanted, 1 - High Priority
